create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  message text not null,
  category text not null,
  is_reviewed boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "Anyone can submit anonymous feedback" on public.feedback;
create policy "Anyone can submit anonymous feedback"
  on public.feedback
  for insert
  with check (true);

drop policy if exists "Only authenticated admin can read feedback" on public.feedback;
create policy "Only authenticated admin can read feedback"
  on public.feedback
  for select
  using (auth.role() = 'authenticated');

drop policy if exists "Only authenticated admin can update feedback" on public.feedback;
create policy "Only authenticated admin can update feedback"
  on public.feedback
  for update
  using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

drop policy if exists "Only authenticated admin can delete feedback" on public.feedback;
create policy "Only authenticated admin can delete feedback"
  on public.feedback
  for delete
  using (auth.role() = 'authenticated');

alter publication supabase_realtime add table public.feedback;

select tablename, polname, polcmd
from pg_policies
where tablename = 'feedback';
